## AmpliconSeqFitnessCompetitionAnalysis.R by Rohan Maddamsetti
## This script analyzes the fitness competition data generated by barcoded Illumina sequencing by Andrea Weiss.

library(tidyverse)

## IMPORTANT NOTE 1: The first six and last six samples in the last row of the plate were switched.
## This is easy to see in the data. There is a correspondingly easy fix, which is to just switch
## the labels for the p15A ancestral clone competition and the pUC ancestral clone competition.

## IMPORTANT NOTE 2: evolved pUC clones 6 and 10 lost the pUC plasmid. So, their fitnesses should be more similar
## to the no_plasmid clones than the other pUC clones.

## IMPORTANT TODO: calculate the fitness of each clone in each experiment.
## IMPORTANT TODO: calculate the fitness of group (no plasmid, p15A, pUC) in each experiment.

amplicon.seq.data <- read.csv("../data/AmpliconSeq-fitness-competition-data/AmpliconSeqData-August-07-2023.csv") %>%
    ## use purrr::map2 black magic to make a column using values in two other columns:
    ## https://github.com/rstudio/cheatsheets/blob/main/purrr.pdf
    ## https://dcl-prog.stanford.edu/purrr-parallel.html
    ## populations 6 and 10 from the pUC treatment lost the pUC plasmid.
    mutate(lost_pUC = map2_lgl(.x=Plasmid, .y=Ancestral_Strain,  .f= ~ ifelse(.x=="pUC" && .y %in% c("RM7.107.45", "RM7.107.56"), TRUE, FALSE))) %>%
    ## we want to encode the lost_pUC state separately.
    mutate(EvolvedPlasmid = ifelse(lost_pUC, "lost pUC", Plasmid)) %>%
    ## odd place to make Plasmid a factor, but need to do it after generating the EvolvedPlasmid column,
    ## so that it gets string values rather than integer factor values.
    mutate(Plasmid = as.factor(Plasmid)) %>%
    mutate(EvolvedPlasmid = as.factor(EvolvedPlasmid)) %>%
    mutate(ExperimentalPopulation = as.factor(ExperimentalPopulation)) %>%
    mutate(CompetitionDay = as.factor(CompetitionDay)) %>%
    ## swap the labels of the ancestral pUC and ancestral p15A competitions (see IMPORTANT NOTE 1).
    mutate(CloneMixtureType = case_when(
               CloneMixtureType == "p15aAncestralClones" ~ "pUCAncestralClones",
               CloneMixtureType == "pUCAncestralClones" ~ "p15aAncestralClones",
               TRUE ~ CloneMixtureType))


################################################################################################
## analyze the competitions involving all 30 evolved clones.
evolved.clone.competition.data <- amplicon.seq.data %>% filter(CloneMixtureType == "AllEvolvedClones")


########################
## Let's analyze the competitions preconditioned in LB.
evolved.LB.preconditioned.data <- evolved.clone.competition.data %>% filter(PreconditioningEnvironment=="LB")

## 1) All 30 evolved clones, preconditioned in LB separately, and competition in LB.
evolved.LB.preconditioned.LB.competition.data <- evolved.LB.preconditioned.data %>%
    filter(CompetitionDay == 0  | CompetitionEnvironment=="LB")

## let's first plot a stacked bar plot of abundances at each timepoint.
evolved.LB.preconditioned.LB.competition.plot <- ggplot(
    data=evolved.LB.preconditioned.LB.competition.data,
    aes(x=CompetitionDay, y = ReadCount, fill=EvolvedPlasmid)) +
    facet_wrap(.~Replicate) +
    geom_bar(stat="identity", position="fill") +
    theme_classic() +
    theme(legend.position="top") +
    ggtitle("LB preconditioning, LB competition")
## save the plot
ggsave("../results/amplicon-seq-LB-preconditioning-LB-competition.pdf",
       evolved.LB.preconditioned.LB.competition.plot, width=10)


## 2) All 30 evolved clones, preconditioned in LB separately, and competition in LB+Tet50.
evolved.LB.preconditioned.Tet50.competition.data <- evolved.LB.preconditioned.data %>%
    filter(CompetitionDay == 0 | CompetitionEnvironment=="LB_Tet50")

## let's first plot a stacked bar plot of abundances at each timepoint.
evolved.LB.preconditioned.Tet50.competition.plot <- ggplot(
    data=evolved.LB.preconditioned.Tet50.competition.data,
    aes(x=CompetitionDay, y = ReadCount, fill=EvolvedPlasmid)) +
    facet_wrap(.~Replicate) +
    geom_bar(stat="identity", position="fill") +
    theme_classic() +
    theme(legend.position="top") +
    ggtitle("LB preconditioning, LB+Tet50 competition")
## save the plot
ggsave("../results/amplicon-seq-LB-preconditioning-Tet50-competition.pdf",
       evolved.LB.preconditioned.Tet50.competition.plot, width=10)


########################
## Let's analyze the competitions preconditioned in LB+Tet50.
evolved.Tet50.preconditioned.data <- evolved.clone.competition.data %>% filter(PreconditioningEnvironment=="LB_Tet50")

## 3) All 30 evolved clones, preconditioned in LB+Tet50 separately, and competition in LB.
evolved.Tet50.preconditioned.LB.competition.data <- evolved.Tet50.preconditioned.data %>%
    filter(CompetitionDay == 0 | CompetitionEnvironment=="LB")

## let's first plot a stacked bar plot of abundances at each timepoint.
evolved.Tet50.preconditioned.LB.competition.plot <- ggplot(
    data=evolved.Tet50.preconditioned.LB.competition.data,
    aes(x=CompetitionDay, y = ReadCount, fill=EvolvedPlasmid)) +
    facet_wrap(.~Replicate) +
    geom_bar(stat="identity", position="fill") +
    theme_classic() +
    theme(legend.position="top") +
    ggtitle("LB+Tet50 preconditioning, LB competition")
## save the plot
ggsave("../results/amplicon-seq-Tet50-preconditioning-LB-competition.pdf",
       evolved.Tet50.preconditioned.LB.competition.plot, width=10)


## 4) All 30 evolved clones, preconditioned in LB+Tet50 separately, and competition in LB+Tet50.
evolved.Tet50.preconditioned.Tet50.competition.data <- evolved.Tet50.preconditioned.data %>%
    filter(CompetitionDay == 0 | CompetitionEnvironment=="LB_Tet50")

## let's first plot a stacked bar plot of abundances at each timepoint.
evolved.Tet50.preconditioned.Tet50.competition.plot <- ggplot(
    data=evolved.Tet50.preconditioned.Tet50.competition.data,
    aes(x=CompetitionDay, y = ReadCount, fill=EvolvedPlasmid)) +
    facet_wrap(.~Replicate) +
    geom_bar(stat="identity", position="fill") +
    theme_classic() +
    theme(legend.position="top") +
    ggtitle("LB+Tet50 preconditioning, LB+Tet50 competition")
## save the plot
ggsave("../results/amplicon-seq-Tet50-preconditioning-Tet50-competition.pdf",
       evolved.Tet50.preconditioned.Tet50.competition.plot, width=10)

################################################################################################
## 5) All 30 ancestral clones, preconditioned in LB and competition in LB.
all.ancestral.clone.competition.data <- amplicon.seq.data %>% filter(CloneMixtureType == "AllAncestralClones")

all.ancestral.clone.competition.plot <- ggplot(
    data=all.ancestral.clone.competition.data,
    aes(x=CompetitionDay, y = ReadCount, fill=Plasmid)) +
    facet_wrap(.~Replicate) +
    geom_bar(stat="identity", position="fill") +
    theme_classic() +
    theme(legend.position="top") +
    ggtitle("All ancestral clones")
## save the plot
ggsave("../results/amplicon-seq-all-ancestral-clone-competition.pdf",
       all.ancestral.clone.competition.plot, width=10)


## 6) 10 ancestral no_plasmid clones, preconditioned in LB and competition in LB.
no.plasmid.ancestral.clone.competition.data <- amplicon.seq.data %>%
    filter(CloneMixtureType == "NoPlasmidAncestralClones")

no.plasmid.ancestral.clone.competition.plot <- ggplot(
    data=no.plasmid.ancestral.clone.competition.data,
    aes(x=CompetitionDay, y = ReadCount, fill=ExperimentalPopulation)) +
    facet_wrap(.~Replicate) +
    geom_bar(stat="identity", position="fill") +
    theme_classic() +
    theme(legend.position="top") +
    ggtitle("No-plasmid ancestral clones")
## save the plot
ggsave("../results/amplicon-seq-no_plasmid-ancestral-clone-competition.pdf",
       no.plasmid.ancestral.clone.competition.plot, width=10)


### CRITICALLY IMPORTANT TODO: FIX THE LABELS!

## 7) 10 ancestral p15A clones, preconditioned in LB and competition in LB.
p15A.ancestral.clone.competition.data <- amplicon.seq.data %>%
    filter(CloneMixtureType == "p15aAncestralClones")

p15A.ancestral.clone.competition.plot <- ggplot(
    data=p15A.ancestral.clone.competition.data,
    aes(x=CompetitionDay, y = ReadCount, fill=ExperimentalPopulation)) +
    facet_wrap(.~Replicate) +
    geom_bar(stat="identity", position="fill") +
    theme_classic() +
    theme(legend.position="top") +
    ggtitle("p15A ancestral clones")
## save the plot
ggsave("../results/amplicon-seq-p15A-ancestral-clone-competition.pdf",
       p15A.ancestral.clone.competition.plot, width=10)


## 8) 10 ancestral pUC clones, preconditioned in LB and competition in LB.
pUC.ancestral.clone.competition.data <- amplicon.seq.data %>%
    filter(CloneMixtureType == "pUCAncestralClones")

pUC.ancestral.clone.competition.plot <- ggplot(
    data=pUC.ancestral.clone.competition.data,
    aes(x=CompetitionDay, y = ReadCount, fill=ExperimentalPopulation)) +
    facet_wrap(.~Replicate) +
    geom_bar(stat="identity", position="fill") +
    theme_classic() +
    theme(legend.position="top") +
    ggtitle("pUC ancestral clones")
## save the plot
ggsave("../results/amplicon-seq-pUC-ancestral-clone-competition.pdf",
       pUC.ancestral.clone.competition.plot, width=10)
